import type { Continent, Country, Region } from './types';

export const REGION_ORDER: Region[] = [
  'east_asia',
  'southeast_asia',
  'south_asia',
  'central_asia',
  'middle_east',
  'northern_europe',
  'western_europe',
  'southern_europe',
  'eastern_europe',
  'north_africa',
  'west_africa',
  'central_africa',
  'east_africa',
  'southern_africa',
  'north_america',
  'central_america',
  'south_america',
  'oceania',
  'antarctica',
];

export const CONTINENT_ORDER: Continent[] = [
  'asia',
  'europe',
  'africa',
  'north_america',
  'central_america',
  'south_america',
  'oceania',
  'antarctica',
];

export const REGION_TO_CONTINENT: Record<Region, Continent> = {
  east_asia: 'asia',
  southeast_asia: 'asia',
  south_asia: 'asia',
  central_asia: 'asia',
  middle_east: 'asia',
  northern_europe: 'europe',
  western_europe: 'europe',
  southern_europe: 'europe',
  eastern_europe: 'europe',
  north_africa: 'africa',
  west_africa: 'africa',
  central_africa: 'africa',
  east_africa: 'africa',
  southern_africa: 'africa',
  north_america: 'north_america',
  central_america: 'central_america',
  south_america: 'south_america',
  oceania: 'oceania',
  antarctica: 'antarctica',
};

export const REGIONS_BY_CONTINENT: Record<Continent, Region[]> =
  CONTINENT_ORDER.reduce(
    (acc, continent) => {
      acc[continent] = REGION_ORDER.filter(
        (region) => REGION_TO_CONTINENT[region] === continent
      );
      return acc;
    },
    {} as Record<Continent, Region[]>
  );

export const COUNTRIES: Country[] = [
  {
    id: '004',
    iso_a3: 'AFG',
    name_ja: 'アフガニスタン',
    name_en: 'Afghanistan',
    region: 'south_asia',
  },
  {
    id: '008',
    iso_a3: 'ALB',
    name_ja: 'アルバニア',
    name_en: 'Albania',
    region: 'southern_europe',
  },
  {
    id: '010',
    iso_a3: 'ATA',
    name_ja: '南極',
    name_en: 'Antarctica',
    region: 'antarctica',
  },
  {
    id: '012',
    iso_a3: 'DZA',
    name_ja: 'アルジェリア',
    name_en: 'Algeria',
    region: 'north_africa',
  },
  {
    id: '024',
    iso_a3: 'AGO',
    name_ja: 'アンゴラ',
    name_en: 'Angola',
    region: 'southern_africa',
  },
  {
    id: '031',
    iso_a3: 'AZE',
    name_ja: 'アゼルバイジャン',
    name_en: 'Azerbaijan',
    region: 'middle_east',
  },
  {
    id: '032',
    iso_a3: 'ARG',
    name_ja: 'アルゼンチン',
    name_en: 'Argentina',
    region: 'south_america',
  },
  {
    id: '036',
    iso_a3: 'AUS',
    name_ja: 'オーストラリア',
    name_en: 'Australia',
    region: 'oceania',
  },
  {
    id: '040',
    iso_a3: 'AUT',
    name_ja: 'オーストリア',
    name_en: 'Austria',
    region: 'western_europe',
  },
  {
    id: '044',
    iso_a3: 'BHS',
    name_ja: 'バハマ',
    name_en: 'Bahamas',
    region: 'central_america',
  },
  {
    id: '050',
    iso_a3: 'BGD',
    name_ja: 'バングラデシュ',
    name_en: 'Bangladesh',
    region: 'south_asia',
  },
  {
    id: '051',
    iso_a3: 'ARM',
    name_ja: 'アルメニア',
    name_en: 'Armenia',
    region: 'middle_east',
  },
  {
    id: '056',
    iso_a3: 'BEL',
    name_ja: 'ベルギー',
    name_en: 'Belgium',
    region: 'western_europe',
  },
  {
    id: '064',
    iso_a3: 'BTN',
    name_ja: 'ブータン',
    name_en: 'Bhutan',
    region: 'south_asia',
  },
  {
    id: '068',
    iso_a3: 'BOL',
    name_ja: 'ボリビア',
    name_en: 'Bolivia',
    region: 'south_america',
  },
  {
    id: '070',
    iso_a3: 'BIH',
    name_ja: 'ボスニア・ヘルツェゴビナ',
    name_en: 'Bosnia and Herzegovina',
    region: 'southern_europe',
  },
  {
    id: '072',
    iso_a3: 'BWA',
    name_ja: 'ボツワナ',
    name_en: 'Botswana',
    region: 'southern_africa',
  },
  {
    id: '076',
    iso_a3: 'BRA',
    name_ja: 'ブラジル',
    name_en: 'Brazil',
    region: 'south_america',
  },
  {
    id: '084',
    iso_a3: 'BLZ',
    name_ja: 'ベリーズ',
    name_en: 'Belize',
    region: 'central_america',
  },
  {
    id: '090',
    iso_a3: 'SLB',
    name_ja: 'ソロモン諸島',
    name_en: 'Solomon Islands',
    region: 'oceania',
  },
  {
    id: '096',
    iso_a3: 'BRN',
    name_ja: 'ブルネイ',
    name_en: 'Brunei',
    region: 'southeast_asia',
  },
  {
    id: '100',
    iso_a3: 'BGR',
    name_ja: 'ブルガリア',
    name_en: 'Bulgaria',
    region: 'eastern_europe',
  },
  {
    id: '104',
    iso_a3: 'MMR',
    name_ja: 'ミャンマー',
    name_en: 'Myanmar',
    region: 'southeast_asia',
  },
  {
    id: '108',
    iso_a3: 'BDI',
    name_ja: 'ブルンジ',
    name_en: 'Burundi',
    region: 'east_africa',
  },
  {
    id: '112',
    iso_a3: 'BLR',
    name_ja: 'ベラルーシ',
    name_en: 'Belarus',
    region: 'eastern_europe',
  },
  {
    id: '116',
    iso_a3: 'KHM',
    name_ja: 'カンボジア',
    name_en: 'Cambodia',
    region: 'southeast_asia',
  },
  {
    id: '120',
    iso_a3: 'CMR',
    name_ja: 'カメルーン',
    name_en: 'Cameroon',
    region: 'central_africa',
  },
  {
    id: '124',
    iso_a3: 'CAN',
    name_ja: 'カナダ',
    name_en: 'Canada',
    region: 'north_america',
  },
  {
    id: '140',
    iso_a3: 'CAF',
    name_ja: '中央アフリカ共和国',
    name_en: 'Central African Republic',
    region: 'central_africa',
  },
  {
    id: '144',
    iso_a3: 'LKA',
    name_ja: 'スリランカ',
    name_en: 'Sri Lanka',
    region: 'south_asia',
  },
  {
    id: '148',
    iso_a3: 'TCD',
    name_ja: 'チャド',
    name_en: 'Chad',
    region: 'central_africa',
  },
  {
    id: '152',
    iso_a3: 'CHL',
    name_ja: 'チリ',
    name_en: 'Chile',
    region: 'south_america',
  },
  {
    id: '156',
    iso_a3: 'CHN',
    name_ja: '中国',
    name_en: 'China',
    region: 'east_asia',
  },
  {
    id: '158',
    iso_a3: 'TWN',
    name_ja: '台湾',
    name_en: 'Taiwan',
    region: 'east_asia',
  },
  {
    id: '170',
    iso_a3: 'COL',
    name_ja: 'コロンビア',
    name_en: 'Colombia',
    region: 'south_america',
  },
  {
    id: '178',
    iso_a3: 'COG',
    name_ja: 'コンゴ共和国',
    name_en: 'Republic of the Congo',
    region: 'central_africa',
  },
  {
    id: '180',
    iso_a3: 'COD',
    name_ja: 'コンゴ民主共和国',
    name_en: 'Democratic Republic of the Congo',
    region: 'central_africa',
  },
  {
    id: '188',
    iso_a3: 'CRI',
    name_ja: 'コスタリカ',
    name_en: 'Costa Rica',
    region: 'central_america',
  },
  {
    id: '191',
    iso_a3: 'HRV',
    name_ja: 'クロアチア',
    name_en: 'Croatia',
    region: 'southern_europe',
  },
  {
    id: '192',
    iso_a3: 'CUB',
    name_ja: 'キューバ',
    name_en: 'Cuba',
    region: 'central_america',
  },
  {
    id: '196',
    iso_a3: 'CYP',
    name_ja: 'キプロス',
    name_en: 'Cyprus',
    region: 'middle_east',
  },
  {
    id: '203',
    iso_a3: 'CZE',
    name_ja: 'チェコ',
    name_en: 'Czechia',
    region: 'eastern_europe',
  },
  {
    id: '204',
    iso_a3: 'BEN',
    name_ja: 'ベナン',
    name_en: 'Benin',
    region: 'west_africa',
  },
  {
    id: '208',
    iso_a3: 'DNK',
    name_ja: 'デンマーク',
    name_en: 'Denmark',
    region: 'northern_europe',
  },
  {
    id: '214',
    iso_a3: 'DOM',
    name_ja: 'ドミニカ共和国',
    name_en: 'Dominican Republic',
    region: 'central_america',
  },
  {
    id: '218',
    iso_a3: 'ECU',
    name_ja: 'エクアドル',
    name_en: 'Ecuador',
    region: 'south_america',
  },
  {
    id: '222',
    iso_a3: 'SLV',
    name_ja: 'エルサルバドル',
    name_en: 'El Salvador',
    region: 'central_america',
  },
  {
    id: '226',
    iso_a3: 'GNQ',
    name_ja: '赤道ギニア',
    name_en: 'Equatorial Guinea',
    region: 'central_africa',
  },
  {
    id: '231',
    iso_a3: 'ETH',
    name_ja: 'エチオピア',
    name_en: 'Ethiopia',
    region: 'east_africa',
  },
  {
    id: '232',
    iso_a3: 'ERI',
    name_ja: 'エリトリア',
    name_en: 'Eritrea',
    region: 'east_africa',
  },
  {
    id: '233',
    iso_a3: 'EST',
    name_ja: 'エストニア',
    name_en: 'Estonia',
    region: 'northern_europe',
  },
  {
    id: '238',
    iso_a3: 'FLK',
    name_ja: 'フォークランド諸島',
    name_en: 'Falkland Islands',
    region: 'south_america',
  },
  {
    id: '242',
    iso_a3: 'FJI',
    name_ja: 'フィジー',
    name_en: 'Fiji',
    region: 'oceania',
  },
  {
    id: '246',
    iso_a3: 'FIN',
    name_ja: 'フィンランド',
    name_en: 'Finland',
    region: 'northern_europe',
  },
  {
    id: '250',
    iso_a3: 'FRA',
    name_ja: 'フランス',
    name_en: 'France',
    region: 'western_europe',
  },
  {
    id: '260',
    iso_a3: 'ATF',
    name_ja: 'フランス領南方・南極地域',
    name_en: 'French Southern Territories',
    region: 'antarctica',
  },
  {
    id: '262',
    iso_a3: 'DJI',
    name_ja: 'ジブチ',
    name_en: 'Djibouti',
    region: 'east_africa',
  },
  {
    id: '266',
    iso_a3: 'GAB',
    name_ja: 'ガボン',
    name_en: 'Gabon',
    region: 'central_africa',
  },
  {
    id: '268',
    iso_a3: 'GEO',
    name_ja: 'ジョージア',
    name_en: 'Georgia',
    region: 'middle_east',
  },
  {
    id: '270',
    iso_a3: 'GMB',
    name_ja: 'ガンビア',
    name_en: 'Gambia',
    region: 'west_africa',
  },
  {
    id: '275',
    iso_a3: 'PSE',
    name_ja: 'パレスチナ',
    name_en: 'Palestine',
    region: 'middle_east',
  },
  {
    id: '276',
    iso_a3: 'DEU',
    name_ja: 'ドイツ',
    name_en: 'Germany',
    region: 'western_europe',
  },
  {
    id: '288',
    iso_a3: 'GHA',
    name_ja: 'ガーナ',
    name_en: 'Ghana',
    region: 'west_africa',
  },
  {
    id: '300',
    iso_a3: 'GRC',
    name_ja: 'ギリシャ',
    name_en: 'Greece',
    region: 'southern_europe',
  },
  {
    id: '304',
    iso_a3: 'GRL',
    name_ja: 'グリーンランド',
    name_en: 'Greenland',
    region: 'north_america',
  },
  {
    id: '320',
    iso_a3: 'GTM',
    name_ja: 'グアテマラ',
    name_en: 'Guatemala',
    region: 'central_america',
  },
  {
    id: '324',
    iso_a3: 'GIN',
    name_ja: 'ギニア',
    name_en: 'Guinea',
    region: 'west_africa',
  },
  {
    id: '328',
    iso_a3: 'GUY',
    name_ja: 'ガイアナ',
    name_en: 'Guyana',
    region: 'south_america',
  },
  {
    id: '332',
    iso_a3: 'HTI',
    name_ja: 'ハイチ',
    name_en: 'Haiti',
    region: 'central_america',
  },
  {
    id: '340',
    iso_a3: 'HND',
    name_ja: 'ホンジュラス',
    name_en: 'Honduras',
    region: 'central_america',
  },
  {
    id: '348',
    iso_a3: 'HUN',
    name_ja: 'ハンガリー',
    name_en: 'Hungary',
    region: 'eastern_europe',
  },
  {
    id: '352',
    iso_a3: 'ISL',
    name_ja: 'アイスランド',
    name_en: 'Iceland',
    region: 'northern_europe',
  },
  {
    id: '356',
    iso_a3: 'IND',
    name_ja: 'インド',
    name_en: 'India',
    region: 'south_asia',
  },
  {
    id: '360',
    iso_a3: 'IDN',
    name_ja: 'インドネシア',
    name_en: 'Indonesia',
    region: 'southeast_asia',
  },
  {
    id: '364',
    iso_a3: 'IRN',
    name_ja: 'イラン',
    name_en: 'Iran',
    region: 'middle_east',
  },
  {
    id: '368',
    iso_a3: 'IRQ',
    name_ja: 'イラク',
    name_en: 'Iraq',
    region: 'middle_east',
  },
  {
    id: '372',
    iso_a3: 'IRL',
    name_ja: 'アイルランド',
    name_en: 'Ireland',
    region: 'northern_europe',
  },
  {
    id: '376',
    iso_a3: 'ISR',
    name_ja: 'イスラエル',
    name_en: 'Israel',
    region: 'middle_east',
  },
  {
    id: '380',
    iso_a3: 'ITA',
    name_ja: 'イタリア',
    name_en: 'Italy',
    region: 'southern_europe',
  },
  {
    id: '384',
    iso_a3: 'CIV',
    name_ja: 'コートジボワール',
    name_en: "Côte d'Ivoire",
    region: 'west_africa',
  },
  {
    id: '388',
    iso_a3: 'JAM',
    name_ja: 'ジャマイカ',
    name_en: 'Jamaica',
    region: 'central_america',
  },
  {
    id: '392',
    iso_a3: 'JPN',
    name_ja: '日本',
    name_en: 'Japan',
    region: 'east_asia',
  },
  {
    id: '398',
    iso_a3: 'KAZ',
    name_ja: 'カザフスタン',
    name_en: 'Kazakhstan',
    region: 'central_asia',
  },
  {
    id: '400',
    iso_a3: 'JOR',
    name_ja: 'ヨルダン',
    name_en: 'Jordan',
    region: 'middle_east',
  },
  {
    id: '404',
    iso_a3: 'KEN',
    name_ja: 'ケニア',
    name_en: 'Kenya',
    region: 'east_africa',
  },
  {
    id: '408',
    iso_a3: 'PRK',
    name_ja: '北朝鮮',
    name_en: 'North Korea',
    region: 'east_asia',
  },
  {
    id: '410',
    iso_a3: 'KOR',
    name_ja: '韓国',
    name_en: 'South Korea',
    region: 'east_asia',
  },
  {
    id: '414',
    iso_a3: 'KWT',
    name_ja: 'クウェート',
    name_en: 'Kuwait',
    region: 'middle_east',
  },
  {
    id: '417',
    iso_a3: 'KGZ',
    name_ja: 'キルギス',
    name_en: 'Kyrgyzstan',
    region: 'central_asia',
  },
  {
    id: '418',
    iso_a3: 'LAO',
    name_ja: 'ラオス',
    name_en: 'Laos',
    region: 'southeast_asia',
  },
  {
    id: '422',
    iso_a3: 'LBN',
    name_ja: 'レバノン',
    name_en: 'Lebanon',
    region: 'middle_east',
  },
  {
    id: '426',
    iso_a3: 'LSO',
    name_ja: 'レソト',
    name_en: 'Lesotho',
    region: 'southern_africa',
  },
  {
    id: '428',
    iso_a3: 'LVA',
    name_ja: 'ラトビア',
    name_en: 'Latvia',
    region: 'northern_europe',
  },
  {
    id: '430',
    iso_a3: 'LBR',
    name_ja: 'リベリア',
    name_en: 'Liberia',
    region: 'west_africa',
  },
  {
    id: '434',
    iso_a3: 'LBY',
    name_ja: 'リビア',
    name_en: 'Libya',
    region: 'north_africa',
  },
  {
    id: '440',
    iso_a3: 'LTU',
    name_ja: 'リトアニア',
    name_en: 'Lithuania',
    region: 'northern_europe',
  },
  {
    id: '442',
    iso_a3: 'LUX',
    name_ja: 'ルクセンブルク',
    name_en: 'Luxembourg',
    region: 'western_europe',
  },
  {
    id: '450',
    iso_a3: 'MDG',
    name_ja: 'マダガスカル',
    name_en: 'Madagascar',
    region: 'east_africa',
  },
  {
    id: '454',
    iso_a3: 'MWI',
    name_ja: 'マラウイ',
    name_en: 'Malawi',
    region: 'southern_africa',
  },
  {
    id: '458',
    iso_a3: 'MYS',
    name_ja: 'マレーシア',
    name_en: 'Malaysia',
    region: 'southeast_asia',
  },
  {
    id: '466',
    iso_a3: 'MLI',
    name_ja: 'マリ',
    name_en: 'Mali',
    region: 'west_africa',
  },
  {
    id: '478',
    iso_a3: 'MRT',
    name_ja: 'モーリタニア',
    name_en: 'Mauritania',
    region: 'west_africa',
  },
  {
    id: '484',
    iso_a3: 'MEX',
    name_ja: 'メキシコ',
    name_en: 'Mexico',
    region: 'north_america',
  },
  {
    id: '496',
    iso_a3: 'MNG',
    name_ja: 'モンゴル',
    name_en: 'Mongolia',
    region: 'east_asia',
  },
  {
    id: '498',
    iso_a3: 'MDA',
    name_ja: 'モルドバ',
    name_en: 'Moldova',
    region: 'eastern_europe',
  },
  {
    id: '499',
    iso_a3: 'MNE',
    name_ja: 'モンテネグロ',
    name_en: 'Montenegro',
    region: 'southern_europe',
  },
  {
    id: '504',
    iso_a3: 'MAR',
    name_ja: 'モロッコ',
    name_en: 'Morocco',
    region: 'north_africa',
  },
  {
    id: '508',
    iso_a3: 'MOZ',
    name_ja: 'モザンビーク',
    name_en: 'Mozambique',
    region: 'southern_africa',
  },
  {
    id: '512',
    iso_a3: 'OMN',
    name_ja: 'オマーン',
    name_en: 'Oman',
    region: 'middle_east',
  },
  {
    id: '516',
    iso_a3: 'NAM',
    name_ja: 'ナミビア',
    name_en: 'Namibia',
    region: 'southern_africa',
  },
  {
    id: '524',
    iso_a3: 'NPL',
    name_ja: 'ネパール',
    name_en: 'Nepal',
    region: 'south_asia',
  },
  {
    id: '528',
    iso_a3: 'NLD',
    name_ja: 'オランダ',
    name_en: 'Netherlands',
    region: 'western_europe',
  },
  {
    id: '540',
    iso_a3: 'NCL',
    name_ja: 'ニューカレドニア',
    name_en: 'New Caledonia',
    region: 'oceania',
  },
  {
    id: '548',
    iso_a3: 'VUT',
    name_ja: 'バヌアツ',
    name_en: 'Vanuatu',
    region: 'oceania',
  },
  {
    id: '554',
    iso_a3: 'NZL',
    name_ja: 'ニュージーランド',
    name_en: 'New Zealand',
    region: 'oceania',
  },
  {
    id: '558',
    iso_a3: 'NIC',
    name_ja: 'ニカラグア',
    name_en: 'Nicaragua',
    region: 'central_america',
  },
  {
    id: '562',
    iso_a3: 'NER',
    name_ja: 'ニジェール',
    name_en: 'Niger',
    region: 'west_africa',
  },
  {
    id: '566',
    iso_a3: 'NGA',
    name_ja: 'ナイジェリア',
    name_en: 'Nigeria',
    region: 'west_africa',
  },
  {
    id: '578',
    iso_a3: 'NOR',
    name_ja: 'ノルウェー',
    name_en: 'Norway',
    region: 'northern_europe',
  },
  {
    id: '586',
    iso_a3: 'PAK',
    name_ja: 'パキスタン',
    name_en: 'Pakistan',
    region: 'south_asia',
  },
  {
    id: '591',
    iso_a3: 'PAN',
    name_ja: 'パナマ',
    name_en: 'Panama',
    region: 'central_america',
  },
  {
    id: '598',
    iso_a3: 'PNG',
    name_ja: 'パプアニューギニア',
    name_en: 'Papua New Guinea',
    region: 'oceania',
  },
  {
    id: '600',
    iso_a3: 'PRY',
    name_ja: 'パラグアイ',
    name_en: 'Paraguay',
    region: 'south_america',
  },
  {
    id: '604',
    iso_a3: 'PER',
    name_ja: 'ペルー',
    name_en: 'Peru',
    region: 'south_america',
  },
  {
    id: '608',
    iso_a3: 'PHL',
    name_ja: 'フィリピン',
    name_en: 'Philippines',
    region: 'southeast_asia',
  },
  {
    id: '616',
    iso_a3: 'POL',
    name_ja: 'ポーランド',
    name_en: 'Poland',
    region: 'eastern_europe',
  },
  {
    id: '620',
    iso_a3: 'PRT',
    name_ja: 'ポルトガル',
    name_en: 'Portugal',
    region: 'southern_europe',
  },
  {
    id: '624',
    iso_a3: 'GNB',
    name_ja: 'ギニアビサウ',
    name_en: 'Guinea-Bissau',
    region: 'west_africa',
  },
  {
    id: '626',
    iso_a3: 'TLS',
    name_ja: '東ティモール',
    name_en: 'Timor-Leste',
    region: 'southeast_asia',
  },
  {
    id: '630',
    iso_a3: 'PRI',
    name_ja: 'プエルトリコ',
    name_en: 'Puerto Rico',
    region: 'central_america',
  },
  {
    id: '634',
    iso_a3: 'QAT',
    name_ja: 'カタール',
    name_en: 'Qatar',
    region: 'middle_east',
  },
  {
    id: '642',
    iso_a3: 'ROU',
    name_ja: 'ルーマニア',
    name_en: 'Romania',
    region: 'eastern_europe',
  },
  {
    id: '643',
    iso_a3: 'RUS',
    name_ja: 'ロシア',
    name_en: 'Russia',
    region: 'eastern_europe',
  },
  {
    id: '646',
    iso_a3: 'RWA',
    name_ja: 'ルワンダ',
    name_en: 'Rwanda',
    region: 'east_africa',
  },
  {
    id: '682',
    iso_a3: 'SAU',
    name_ja: 'サウジアラビア',
    name_en: 'Saudi Arabia',
    region: 'middle_east',
  },
  {
    id: '686',
    iso_a3: 'SEN',
    name_ja: 'セネガル',
    name_en: 'Senegal',
    region: 'west_africa',
  },
  {
    id: '688',
    iso_a3: 'SRB',
    name_ja: 'セルビア',
    name_en: 'Serbia',
    region: 'southern_europe',
  },
  {
    id: '694',
    iso_a3: 'SLE',
    name_ja: 'シエラレオネ',
    name_en: 'Sierra Leone',
    region: 'west_africa',
  },
  {
    id: '703',
    iso_a3: 'SVK',
    name_ja: 'スロバキア',
    name_en: 'Slovakia',
    region: 'eastern_europe',
  },
  {
    id: '704',
    iso_a3: 'VNM',
    name_ja: 'ベトナム',
    name_en: 'Vietnam',
    region: 'southeast_asia',
  },
  {
    id: '705',
    iso_a3: 'SVN',
    name_ja: 'スロベニア',
    name_en: 'Slovenia',
    region: 'southern_europe',
  },
  {
    id: '706',
    iso_a3: 'SOM',
    name_ja: 'ソマリア',
    name_en: 'Somalia',
    region: 'east_africa',
  },
  {
    id: '710',
    iso_a3: 'ZAF',
    name_ja: '南アフリカ',
    name_en: 'South Africa',
    region: 'southern_africa',
  },
  {
    id: '716',
    iso_a3: 'ZWE',
    name_ja: 'ジンバブエ',
    name_en: 'Zimbabwe',
    region: 'southern_africa',
  },
  {
    id: '724',
    iso_a3: 'ESP',
    name_ja: 'スペイン',
    name_en: 'Spain',
    region: 'southern_europe',
  },
  {
    id: '728',
    iso_a3: 'SSD',
    name_ja: '南スーダン',
    name_en: 'South Sudan',
    region: 'east_africa',
  },
  {
    id: '729',
    iso_a3: 'SDN',
    name_ja: 'スーダン',
    name_en: 'Sudan',
    region: 'north_africa',
  },
  {
    id: '732',
    iso_a3: 'ESH',
    name_ja: '西サハラ',
    name_en: 'Western Sahara',
    region: 'north_africa',
  },
  {
    id: '740',
    iso_a3: 'SUR',
    name_ja: 'スリナム',
    name_en: 'Suriname',
    region: 'south_america',
  },
  {
    id: '748',
    iso_a3: 'SWZ',
    name_ja: 'エスワティニ',
    name_en: 'Eswatini',
    region: 'southern_africa',
  },
  {
    id: '752',
    iso_a3: 'SWE',
    name_ja: 'スウェーデン',
    name_en: 'Sweden',
    region: 'northern_europe',
  },
  {
    id: '756',
    iso_a3: 'CHE',
    name_ja: 'スイス',
    name_en: 'Switzerland',
    region: 'western_europe',
  },
  {
    id: '760',
    iso_a3: 'SYR',
    name_ja: 'シリア',
    name_en: 'Syria',
    region: 'middle_east',
  },
  {
    id: '762',
    iso_a3: 'TJK',
    name_ja: 'タジキスタン',
    name_en: 'Tajikistan',
    region: 'central_asia',
  },
  {
    id: '764',
    iso_a3: 'THA',
    name_ja: 'タイ',
    name_en: 'Thailand',
    region: 'southeast_asia',
  },
  {
    id: '768',
    iso_a3: 'TGO',
    name_ja: 'トーゴ',
    name_en: 'Togo',
    region: 'west_africa',
  },
  {
    id: '780',
    iso_a3: 'TTO',
    name_ja: 'トリニダード・トバゴ',
    name_en: 'Trinidad and Tobago',
    region: 'central_america',
  },
  {
    id: '784',
    iso_a3: 'ARE',
    name_ja: 'アラブ首長国連邦',
    name_en: 'United Arab Emirates',
    region: 'middle_east',
  },
  {
    id: '788',
    iso_a3: 'TUN',
    name_ja: 'チュニジア',
    name_en: 'Tunisia',
    region: 'north_africa',
  },
  {
    id: '792',
    iso_a3: 'TUR',
    name_ja: 'トルコ',
    name_en: 'Turkey',
    region: 'middle_east',
  },
  {
    id: '795',
    iso_a3: 'TKM',
    name_ja: 'トルクメニスタン',
    name_en: 'Turkmenistan',
    region: 'central_asia',
  },
  {
    id: '800',
    iso_a3: 'UGA',
    name_ja: 'ウガンダ',
    name_en: 'Uganda',
    region: 'east_africa',
  },
  {
    id: '804',
    iso_a3: 'UKR',
    name_ja: 'ウクライナ',
    name_en: 'Ukraine',
    region: 'eastern_europe',
  },
  {
    id: '807',
    iso_a3: 'MKD',
    name_ja: '北マケドニア',
    name_en: 'North Macedonia',
    region: 'southern_europe',
  },
  {
    id: '818',
    iso_a3: 'EGY',
    name_ja: 'エジプト',
    name_en: 'Egypt',
    region: 'north_africa',
  },
  {
    id: '826',
    iso_a3: 'GBR',
    name_ja: 'イギリス',
    name_en: 'United Kingdom',
    region: 'northern_europe',
  },
  {
    id: '834',
    iso_a3: 'TZA',
    name_ja: 'タンザニア',
    name_en: 'Tanzania',
    region: 'east_africa',
  },
  {
    id: '840',
    iso_a3: 'USA',
    name_ja: 'アメリカ合衆国',
    name_en: 'United States of America',
    region: 'north_america',
  },
  {
    id: '854',
    iso_a3: 'BFA',
    name_ja: 'ブルキナファソ',
    name_en: 'Burkina Faso',
    region: 'west_africa',
  },
  {
    id: '858',
    iso_a3: 'URY',
    name_ja: 'ウルグアイ',
    name_en: 'Uruguay',
    region: 'south_america',
  },
  {
    id: '860',
    iso_a3: 'UZB',
    name_ja: 'ウズベキスタン',
    name_en: 'Uzbekistan',
    region: 'central_asia',
  },
  {
    id: '862',
    iso_a3: 'VEN',
    name_ja: 'ベネズエラ',
    name_en: 'Venezuela',
    region: 'south_america',
  },
  {
    id: '887',
    iso_a3: 'YEM',
    name_ja: 'イエメン',
    name_en: 'Yemen',
    region: 'middle_east',
  },
  {
    id: '894',
    iso_a3: 'ZMB',
    name_ja: 'ザンビア',
    name_en: 'Zambia',
    region: 'southern_africa',
  },
  {
    id: 'x-kos',
    iso_a3: 'XKX',
    name_ja: 'コソボ',
    name_en: 'Kosovo',
    region: 'southern_europe',
  },
  {
    id: 'x-ncy',
    iso_a3: 'XNC',
    name_ja: '北キプロス',
    name_en: 'Northern Cyprus',
    region: 'middle_east',
  },
  {
    id: 'x-som',
    iso_a3: 'XSL',
    name_ja: 'ソマリランド',
    name_en: 'Somaliland',
    region: 'east_africa',
  },
];

const NAME_TO_ID: Record<string, string> = {
  'Bosnia and Herz.': '070',
  'Central African Rep.': '140',
  'Dem. Rep. Congo': '180',
  'Dominican Rep.': '214',
  'Eq. Guinea': '226',
  'Falkland Is.': '238',
  'Fr. S. Antarctic Lands': '260',
  'Solomon Is.': '090',
  'S. Sudan': '728',
  'W. Sahara': '732',
  eSwatini: '748',
  Macedonia: '807',
  'United States of America': '840',
  Kosovo: 'x-kos',
  'N. Cyprus': 'x-ncy',
  Somaliland: 'x-som',
};

export function resolveCountryId(
  geoId: string | undefined,
  geoName: string | undefined
): string | null {
  if (geoId) return geoId;
  if (geoName && NAME_TO_ID[geoName]) return NAME_TO_ID[geoName];
  return null;
}

export const COUNTRY_BY_ID: Map<string, Country> = new Map(
  COUNTRIES.map((c) => [c.id, c])
);

export const COUNTRIES_BY_REGION: Record<Region, Country[]> =
  REGION_ORDER.reduce(
    (acc, r) => {
      acc[r] = COUNTRIES.filter((country) => country.region === r).sort(
        (a, b) => a.name_ja.localeCompare(b.name_ja, 'ja')
      );
      return acc;
    },
    {} as Record<Region, Country[]>
  );

export const COUNTRIES_BY_CONTINENT: Record<Continent, Country[]> =
  CONTINENT_ORDER.reduce(
    (acc, continent) => {
      acc[continent] = COUNTRIES.filter(
        (country) => REGION_TO_CONTINENT[country.region] === continent
      );
      return acc;
    },
    {} as Record<Continent, Country[]>
  );
